---
# By setting these environment parameters in a dict we circumvent the confusing
# way that default(omit) is externally presented by Ansible.
- name: Set OpenStack credentials
  set_fact:
    os_manila_mount_credentials:
      OS_CLOUD: "{{ (os_manila_mount_os_config_name | default(omit)) if os_manila_mount_auth_type == 'cloud' else omit }}"
      OS_PROJECT_DOMAIN_NAME: "{{ os_manila_mount_auth.project_domain_name | default(omit) }}"
      OS_USER_DOMAIN_NAME: "{{ os_manila_mount_auth.user_domain_name | default(omit) }}"
      OS_PROJECT_NAME: "{{ os_manila_mount_auth.project_name | default(omit) }}"
      OS_USERNAME: "{{ os_manila_mount_auth.username | default(omit) }}"
      OS_PASSWORD: "{{ os_manila_mount_auth.password | default(omit) }}"
      OS_AUTH_URL: "{{ os_manila_mount_auth.auth_url | default(omit) }}"

- name: Get manila access info
  os_manila_share:
    name: "{{ item.key }}"
    user: "{{ os_manila_mount_share_user }}"
    protocol: "{{ os_manila_mount_share_protocol }}"
    mock: "{{ item.key if ( os_manila_mock | default('false') | bool) else omit }}"
  environment: "{{ os_manila_mount_credentials }}"
  register: os_manila_mount_share
  loop: "{{ os_manila_mount_configurations | dict2items }}"

- name: Take facts from manila
  set_fact:
    os_manila_mount_facts: "{{ os_manila_mount_facts | default({}) | combine( { item.details.name : item.details } ) }}" # a dict of results from library/os_manila_share, keyed by share name
  loop: "{{ os_manila_mount_share.results}}"