---
- name: Ensure supported protocol requested
  fail:
    msg: "Sorry, we only support CEPHFS right now."
  when: os_manila_mount_share_protocol != "CEPHFS"

- name: Get manila access info
  os_manila_share:
    name: "{{ os_manila_mount_share_name }}"
    user: "{{ os_manila_mount_share_user }}"
    protocol: "{{ os_manila_mount_share_protocol }}"
  register: os_manila_mount_share
  environment:
      OS_CLOUD: "{{ os_manila_mount_os_config_name }}"
  become: yes

- name: Take config from manila
  set_fact:
    os_manila_mount_host: "{{ os_manila_mount_share.details.host }}"
    os_manila_mount_access_key: "{{ os_manila_mount_share.details.access_key }}"
    os_manila_mount_mountpoint: "{{ os_manila_mount_share.details.path }}"

- name: Install Ceph Jewl noarch Repo
  yum_repository:
    name: ceph-jewl-noarch
    description: Ceph Jewl Repo
    baseurl: "{{ os_manila_mount_ceph_repo_base }}/noarch/"
    gpgkey: https://git.ceph.com/?p=ceph.git;a=blob_plain;f=keys/release.asc
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  become: yes

- name: Install Ceph Jewl Repo
  yum_repository:
    name: ceph-jewl-arch
    description: Ceph Jewl Repo
    baseurl: "{{ os_manila_mount_ceph_repo_base }}/$basearch/"
    gpgkey: https://git.ceph.com/?p=ceph.git;a=blob_plain;f=keys/release.asc
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  become: yes

- name: Install ceph packages for mount and unmount
  yum: name=epel-release,ceph-common,ceph-fuse,fuse
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  become: yes

- name: Ensure ceph conf directory
  file:
    path: "{{ os_manila_mount_ceph_conf_path }}"
    state: directory
    mode: 0700
    owner: root
    group: root
  become: yes

- name: Configure ceph.conf using os_manila_mount_host
  template:
    src: ceph.conf.j2
    dest: "{{ os_manila_mount_ceph_conf_path }}/ceph.conf"
    owner: root
    group: root
    mode: 0600
  become: yes

- name: Add user keyring with os_manila_mount_access_key
  template:
    src: keyring.j2
    dest: "{{ os_manila_mount_ceph_conf_path }}/{{ os_manila_mount_share_user }}.keyring"
    owner: root
    group: root
    mode: 0600
  become: yes

- name: Ensure mount directory exists
  file:
    path: "{{ os_manila_mount_path }}"
    state: directory
    owner: "{{ os_manila_mount_user }}"
    group: "{{ os_manila_mount_group }}"
    mode: "{{ os_manila_mount_mode }}"
  become: yes

# Using _netdev as a filesystem option prevents the mount from blocking early boot
# before networking is initialised
- name: Mount the home directory from the Ceph cluster
  mount:
    path: "{{ os_manila_mount_path }}"
    src: "id={{ os_manila_mount_share_user }},conf={{ os_manila_mount_ceph_conf_path}}/ceph.conf,keyring={{ os_manila_mount_ceph_conf_path }}/{{ os_manila_mount_share_user }}.keyring,client-mountpoint={{ os_manila_mount_mountpoint }}"
    fstype: fuse.ceph
    state: mounted
    opts: "_netdev,noatime"
  become: yes

- name: Ensure mounted directory has correct permissions
  file:
    path: "{{ os_manila_mount_path }}"
    state: directory
    owner: "{{ os_manila_mount_user }}"
    group: "{{ os_manila_mount_group }}"
    mode: "{{ os_manila_mount_mode }}"
  become: yes
