---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
- name: Include lookup tasks
  ansible.builtin.include_tasks: lookup.yml
- name: Include mount tasks
  ansible.builtin.include_tasks: mount.yml
