---
# Perform a lookup if this module has not previously been invoked in that mode.
- include: "lookup.yml"
  when: os_manila_mount_host is not defined or
        os_manila_mount_export is not defined or
        os_manila_mount_access_key is not defined

- name: Ensure supported protocol requested
  fail:
    msg: "Sorry, we only support CEPHFS right now."
  when: os_manila_mount_share_protocol != "CEPHFS"

- block:
    - name: Add Ceph reposity
      yum_repository:
        name: "centos-ceph-{{ os_manila_mount_ceph_version }}"
        description: CentOS Storage SIG repo for ceph luminous
        baseurl: "{{ os_manila_mount_ceph_repo_base }}"
        gpgkey: "{{ os_manila_mount_ceph_repo_key | default(omit) }}"
    - name: Install relevant yum packages
      yum:
        name:
          - epel-release
          - ceph-common
  when:
    - ansible_os_family == 'RedHat'
    - os_manila_mount_pkgs_install | default(true) | bool
  become: yes

- name: Ensure ceph conf directory exists
  file:
    path: "{{ os_manila_mount_ceph_conf_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: yes

- name: Configure ceph.conf using os_manila_mount_host
  template:
    src: ceph.conf.j2
    dest: "{{ os_manila_mount_ceph_conf_path }}/ceph.conf"
    owner: root
    group: root
    mode: 0600
  become: yes

- name: Ensure mount directory exists
  file:
    path: "{{ value.mount_path }}"
    state: directory
    owner: "{{ value.mount_user }}"
    group: "{{ value._mount_group }}"
    mode: "{{ value.mount_mode }}"
  become: yes
  loop: "{{ os_manila_mount_configurations | dict2items }}"

# Using _netdev as a filesystem option prevents the mount from blocking early boot
# before networking is initialised

- name: Write Ceph client secret
  copy:
    dest: "{{ os_manila_mount_ceph_conf_path }}/ceph.client.{{ os_manila_mount_share_user }}.{{ item.key }}.secret"
    content: "{{ item.value.access_key }}"
    mode: 0600
    owner: root
    group: root
  become: yes
  loop: "{{ os_manila_mount_facts | dict2items }}"

- name: FS-Mount the share from the Ceph cluster
  mount:
    path: "{{ os_manila_mount_configurations[item.key].mount_path }}"
    src: "{{ item.host }}:{{ item.export }}"
    fstype: ceph
    state: "{{ os_manila_mount_state }}"
    opts: "_netdev,noatime,name={{ os_manila_mount_share_user }},\
      secretfile=/etc/ceph/ceph.client.{{ os_manila_mount_share_user }}.{{ item.key }}.secret"
    boot: yes
  become: yes
  loop: "{{ os_manila_mount_facts | dict2items }}"

- name: Ensure mounted directory has correct permissions
  file:
    path: "{{ value.mount_path }}"
    state: directory
    owner: "{{ value.mount_user }}"
    group: "{{ value.mount_group }}"
    mode: "{{ value.mount_mode }}"
  become: yes
  loop: "{{ os_manila_mount_configurations | dict2items }}"
